[project]
name = "walkie-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elevenlabs>=2.0.0",
    "httpx>=0.28.1",
    "pyyaml>=6.0",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
